"""
    Granta.BomAnalyticsServices.V1

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: V1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import re  # noqa: F401
from typing import (
    TYPE_CHECKING,
    Any,
    BinaryIO,
    Dict,
    List,
    Optional,
    Union,
)  # noqa: F401

from . import ModelBase, Unset, Unset_Type


if TYPE_CHECKING:
    from datetime import datetime
    import pathlib
    from . import *


class CommonValueWithUnit(ModelBase):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes
    ----------
    swagger_types: Dict[str, str]
        The key is attribute name and the value is attribute type.
    attribute_map: Dict[str, str]
        The key is attribute name and the value is json key in definition.
    subtype_mapping: Dict[str, str]
        The key is the unmangled property name and the value is the corresponding type.
    discriminator: Optional[str]
        Name of the property used as discriminator for subtypes.
    """
    swagger_types: Dict[str, str] = {
        "unit": "str",
        "value": "float",
    }

    attribute_map: Dict[str, str] = {
        "unit": "Unit",
        "value": "Value",
    }

    subtype_mapping: Dict[str, str] = {}

    discriminator: Optional[str] = None

    def __init__(
        self,
        *,
        unit: "Union[str, Unset_Type]" = Unset,
        value: "Union[float, None, Unset_Type]" = Unset,
    ) -> None:
        """CommonValueWithUnit - a model defined in Swagger

        Parameters
        ----------
        unit: str, optional
        value: float, optional
        """
        self._value: Union[float, None, Unset_Type] = Unset
        self._unit: Union[str, Unset_Type] = Unset

        if value is not Unset:
            self.value = value
        if unit is not Unset:
            self.unit = unit

    @property
    def value(self) -> "Union[float, None, Unset_Type]":
        """Gets the value of this CommonValueWithUnit.

        Returns
        -------
        Union[float, None, Unset_Type]
            The value of this CommonValueWithUnit.
        """
        return self._value

    @value.setter
    def value(self, value: "Union[float, None, Unset_Type]") -> None:
        """Sets the value of this CommonValueWithUnit.

        Parameters
        ----------
        value: Union[float, None, Unset_Type]
            The value of this CommonValueWithUnit.
        """
        self._value = value

    @property
    def unit(self) -> "Union[str, Unset_Type]":
        """Gets the unit of this CommonValueWithUnit.

        Returns
        -------
        Union[str, Unset_Type]
            The unit of this CommonValueWithUnit.
        """
        return self._unit

    @unit.setter
    def unit(self, unit: "Union[str, Unset_Type]") -> None:
        """Sets the unit of this CommonValueWithUnit.

        Parameters
        ----------
        unit: Union[str, Unset_Type]
            The unit of this CommonValueWithUnit.
        """
        # Field is not nullable
        if unit is None:
            raise ValueError("Invalid value for 'unit', must not be 'None'")
        self._unit = unit

    @classmethod
    def get_real_child_model(cls, data: Dict[str, str]) -> str:
        """Raises a NotImplementedError for a type without a discriminator defined.

        Parameters
        ----------
        data: ModelBase
            Object representing a subclass of this class

        Raises
        ------
        NotImplementedError
            This class has no discriminator, and hence no subclasses
        """
        raise NotImplementedError()

    def __repr__(self) -> str:
        """For 'print' and 'pprint'"""
        return self.to_str()

    def __eq__(self, other: Any) -> bool:
        """Returns true if both objects are equal"""
        if not isinstance(other, CommonValueWithUnit):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other: Any) -> bool:
        """Returns true if both objects are not equal"""
        return not self == other
