"""
    Granta.BomAnalyticsServices

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: V1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import re  # noqa: F401
from typing import TYPE_CHECKING, Any, Dict, List, Optional  # noqa: F401

from . import ModelBase


if TYPE_CHECKING:
    from . import *


class CommonValueWithUnit(ModelBase):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes
    ----------
    swagger_types: Dict[str, str]
        The key is attribute name and the value is attribute type.
    attribute_map: Dict[str, str]
        The key is attribute name and the value is json key in definition.
    subtype_mapping: Dict[str, str]
        The key is the unmangled property name and the value is the corresponding type.
    discriminator: Optional[str]
        Name of the property used as discriminator for subtypes.
    """
    swagger_types = {
        "unit": "str",
        "value": "float",
    }

    attribute_map = {
        "unit": "Unit",
        "value": "Value",
    }

    subtype_mapping = {}

    discriminator = None

    def __init__(
        self,
        *,
        unit: "Optional[str]" = None,
        value: "Optional[float]" = None,
    ) -> None:
        """CommonValueWithUnit - a model defined in Swagger

        Parameters
        ----------
            unit: str, optional
            value: float, optional
        """
        self._value = None
        self._unit = None

        if value is not None:
            self.value = value
        if unit is not None:
            self.unit = unit

    @property
    def value(self) -> "float":
        """Gets the value of this CommonValueWithUnit.

        Returns
        -------
        float
            The value of this CommonValueWithUnit.
        """
        return self._value

    @value.setter
    def value(self, value: "float") -> None:
        """Sets the value of this CommonValueWithUnit.

        Parameters
        ----------
        value: float
            The value of this CommonValueWithUnit.
        """
        self._value = value

    @property
    def unit(self) -> "str":
        """Gets the unit of this CommonValueWithUnit.

        Returns
        -------
        str
            The unit of this CommonValueWithUnit.
        """
        return self._unit

    @unit.setter
    def unit(self, unit: "str") -> None:
        """Sets the unit of this CommonValueWithUnit.

        Parameters
        ----------
        unit: str
            The unit of this CommonValueWithUnit.
        """
        self._unit = unit

    @classmethod
    def get_real_child_model(cls, data: ModelBase) -> str:
        """Raises a NotImplementedError for a type without a discriminator defined.

        Parameters
        ----------
        data: ModelBase
            Object representing a subclass of this class

        Raises
        ------
        NotImplementedError
            This class has no discriminator, and hence no subclasses
        """
        raise NotImplementedError()

    def __repr__(self) -> str:
        """For 'print' and 'pprint'"""
        return self.to_str()

    def __eq__(self, other: Any) -> bool:
        """Returns true if both objects are equal"""
        if not isinstance(other, CommonValueWithUnit):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other: Any) -> bool:
        """Returns true if both objects are not equal"""
        return not self == other
