"""
    Granta.BomAnalyticsServices

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: V1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import re  # noqa: F401
from typing import TYPE_CHECKING, Any, Dict, List, Optional  # noqa: F401

from . import ModelBase


if TYPE_CHECKING:
    from . import *


class CommonSustainabilityMaterialContributingComponent(ModelBase):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes
    ----------
    swagger_types: Dict[str, str]
        The key is attribute name and the value is attribute type.
    attribute_map: Dict[str, str]
        The key is attribute name and the value is json key in definition.
    subtype_mapping: Dict[str, str]
        The key is the unmangled property name and the value is the corresponding type.
    discriminator: Optional[str]
        Name of the property used as discriminator for subtypes.
    """
    swagger_types = {
        "component_name": "str",
        "component_part_number": "str",
        "material_mass_before_processing": "CommonValueWithUnit",
        "record_reference": "CommonPartReference",
    }

    attribute_map = {
        "component_name": "ComponentName",
        "component_part_number": "ComponentPartNumber",
        "material_mass_before_processing": "MaterialMassBeforeProcessing",
        "record_reference": "RecordReference",
    }

    subtype_mapping = {
        "RecordReference": "CommonPartReference",
        "MaterialMassBeforeProcessing": "CommonValueWithUnit",
    }

    discriminator = None

    def __init__(
        self,
        *,
        component_name: "Optional[str]" = None,
        component_part_number: "Optional[str]" = None,
        material_mass_before_processing: "Optional[CommonValueWithUnit]" = None,
        record_reference: "Optional[CommonPartReference]" = None,
    ) -> None:
        """CommonSustainabilityMaterialContributingComponent - a model defined in Swagger

        Parameters
        ----------
            component_name: str, optional
            component_part_number: str, optional
            material_mass_before_processing: CommonValueWithUnit, optional
            record_reference: CommonPartReference, optional
        """
        self._component_name = None
        self._component_part_number = None
        self._record_reference = None
        self._material_mass_before_processing = None

        if component_name is not None:
            self.component_name = component_name
        if component_part_number is not None:
            self.component_part_number = component_part_number
        if record_reference is not None:
            self.record_reference = record_reference
        if material_mass_before_processing is not None:
            self.material_mass_before_processing = material_mass_before_processing

    @property
    def component_name(self) -> "str":
        """Gets the component_name of this CommonSustainabilityMaterialContributingComponent.

        Returns
        -------
        str
            The component_name of this CommonSustainabilityMaterialContributingComponent.
        """
        return self._component_name

    @component_name.setter
    def component_name(self, component_name: "str") -> None:
        """Sets the component_name of this CommonSustainabilityMaterialContributingComponent.

        Parameters
        ----------
        component_name: str
            The component_name of this CommonSustainabilityMaterialContributingComponent.
        """
        self._component_name = component_name

    @property
    def component_part_number(self) -> "str":
        """Gets the component_part_number of this CommonSustainabilityMaterialContributingComponent.

        Returns
        -------
        str
            The component_part_number of this CommonSustainabilityMaterialContributingComponent.
        """
        return self._component_part_number

    @component_part_number.setter
    def component_part_number(self, component_part_number: "str") -> None:
        """Sets the component_part_number of this CommonSustainabilityMaterialContributingComponent.

        Parameters
        ----------
        component_part_number: str
            The component_part_number of this CommonSustainabilityMaterialContributingComponent.
        """
        self._component_part_number = component_part_number

    @property
    def record_reference(self) -> "CommonPartReference":
        """Gets the record_reference of this CommonSustainabilityMaterialContributingComponent.

        Returns
        -------
        CommonPartReference
            The record_reference of this CommonSustainabilityMaterialContributingComponent.
        """
        return self._record_reference

    @record_reference.setter
    def record_reference(self, record_reference: "CommonPartReference") -> None:
        """Sets the record_reference of this CommonSustainabilityMaterialContributingComponent.

        Parameters
        ----------
        record_reference: CommonPartReference
            The record_reference of this CommonSustainabilityMaterialContributingComponent.
        """
        self._record_reference = record_reference

    @property
    def material_mass_before_processing(self) -> "CommonValueWithUnit":
        """Gets the material_mass_before_processing of this CommonSustainabilityMaterialContributingComponent.

        Returns
        -------
        CommonValueWithUnit
            The material_mass_before_processing of this CommonSustainabilityMaterialContributingComponent.
        """
        return self._material_mass_before_processing

    @material_mass_before_processing.setter
    def material_mass_before_processing(
        self, material_mass_before_processing: "CommonValueWithUnit"
    ) -> None:
        """Sets the material_mass_before_processing of this CommonSustainabilityMaterialContributingComponent.

        Parameters
        ----------
        material_mass_before_processing: CommonValueWithUnit
            The material_mass_before_processing of this CommonSustainabilityMaterialContributingComponent.
        """
        self._material_mass_before_processing = material_mass_before_processing

    @classmethod
    def get_real_child_model(cls, data: ModelBase) -> str:
        """Raises a NotImplementedError for a type without a discriminator defined.

        Parameters
        ----------
        data: ModelBase
            Object representing a subclass of this class

        Raises
        ------
        NotImplementedError
            This class has no discriminator, and hence no subclasses
        """
        raise NotImplementedError()

    def __repr__(self) -> str:
        """For 'print' and 'pprint'"""
        return self.to_str()

    def __eq__(self, other: Any) -> bool:
        """Returns true if both objects are equal"""
        if not isinstance(other, CommonSustainabilityMaterialContributingComponent):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other: Any) -> bool:
        """Returns true if both objects are not equal"""
        return not self == other
