"""
    Granta.BomAnalyticsServices

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: V1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import re  # noqa: F401
from typing import TYPE_CHECKING, Any, Dict, List, Optional  # noqa: F401

from . import ModelBase


if TYPE_CHECKING:
    from . import *


class GetImpactedSubstancesForPartsPart(ModelBase):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes
    ----------
    swagger_types: Dict[str, str]
        The key is attribute name and the value is attribute type.
    attribute_map: Dict[str, str]
        The key is attribute name and the value is json key in definition.
    subtype_mapping: Dict[str, str]
        The key is the unmangled property name and the value is the corresponding type.
    discriminator: Optional[str]
        Name of the property used as discriminator for subtypes.
    """
    swagger_types = {
        "external_identity": "str",
        "id": "str",
        "input_part_number": "str",
        "legislations": "list[CommonLegislationWithImpactedSubstances]",
        "name": "str",
        "reference_type": "str",
        "reference_value": "str",
    }

    attribute_map = {
        "external_identity": "ExternalIdentity",
        "id": "Id",
        "input_part_number": "InputPartNumber",
        "legislations": "Legislations",
        "name": "Name",
        "reference_type": "ReferenceType",
        "reference_value": "ReferenceValue",
    }

    subtype_mapping = {
        "Legislations": "CommonLegislationWithImpactedSubstances",
    }

    discriminator = None

    def __init__(
        self,
        *,
        external_identity: "Optional[str]" = None,
        id: "Optional[str]" = None,
        input_part_number: "Optional[str]" = None,
        legislations: "Optional[List[CommonLegislationWithImpactedSubstances]]" = None,
        name: "Optional[str]" = None,
        reference_type: "Optional[str]" = None,
        reference_value: "Optional[str]" = None,
    ) -> None:
        """GetImpactedSubstancesForPartsPart - a model defined in Swagger

        Parameters
        ----------
            external_identity: str, optional
            id: str, optional
            input_part_number: str, optional
            legislations: List[CommonLegislationWithImpactedSubstances], optional
            name: str, optional
            reference_type: str, optional
            reference_value: str, optional
        """
        self._legislations = None
        self._input_part_number = None
        self._external_identity = None
        self._name = None
        self._reference_type = None
        self._reference_value = None
        self._id = None

        if legislations is not None:
            self.legislations = legislations
        if input_part_number is not None:
            self.input_part_number = input_part_number
        if external_identity is not None:
            self.external_identity = external_identity
        if name is not None:
            self.name = name
        if reference_type is not None:
            self.reference_type = reference_type
        if reference_value is not None:
            self.reference_value = reference_value
        if id is not None:
            self.id = id

    @property
    def legislations(self) -> "list[CommonLegislationWithImpactedSubstances]":
        """Gets the legislations of this GetImpactedSubstancesForPartsPart.

        Returns
        -------
        list[CommonLegislationWithImpactedSubstances]
            The legislations of this GetImpactedSubstancesForPartsPart.
        """
        return self._legislations

    @legislations.setter
    def legislations(
        self, legislations: "list[CommonLegislationWithImpactedSubstances]"
    ) -> None:
        """Sets the legislations of this GetImpactedSubstancesForPartsPart.

        Parameters
        ----------
        legislations: list[CommonLegislationWithImpactedSubstances]
            The legislations of this GetImpactedSubstancesForPartsPart.
        """
        self._legislations = legislations

    @property
    def input_part_number(self) -> "str":
        """Gets the input_part_number of this GetImpactedSubstancesForPartsPart.
        This is set to the value of the PartNumber element in the input BoM.

        Returns
        -------
        str
            The input_part_number of this GetImpactedSubstancesForPartsPart.
        """
        return self._input_part_number

    @input_part_number.setter
    def input_part_number(self, input_part_number: "str") -> None:
        """Sets the input_part_number of this GetImpactedSubstancesForPartsPart.
        This is set to the value of the PartNumber element in the input BoM.

        Parameters
        ----------
        input_part_number: str
            The input_part_number of this GetImpactedSubstancesForPartsPart.
        """
        self._input_part_number = input_part_number

    @property
    def external_identity(self) -> "str":
        """Gets the external_identity of this GetImpactedSubstancesForPartsPart.
        In the input BoM, the ExternalIdentity is intended to be used as a temporary reference populated and used by applications to refer to the item within the BoM. If a value was specified in the input BoM, it will be returned back to the client in this property. If the ExternalIdentity was not present in the input BoM, this property is omitted.

        Returns
        -------
        str
            The external_identity of this GetImpactedSubstancesForPartsPart.
        """
        return self._external_identity

    @external_identity.setter
    def external_identity(self, external_identity: "str") -> None:
        """Sets the external_identity of this GetImpactedSubstancesForPartsPart.
        In the input BoM, the ExternalIdentity is intended to be used as a temporary reference populated and used by applications to refer to the item within the BoM. If a value was specified in the input BoM, it will be returned back to the client in this property. If the ExternalIdentity was not present in the input BoM, this property is omitted.

        Parameters
        ----------
        external_identity: str
            The external_identity of this GetImpactedSubstancesForPartsPart.
        """
        self._external_identity = external_identity

    @property
    def name(self) -> "str":
        """Gets the name of this GetImpactedSubstancesForPartsPart.
        Many elements in the input BoM schema allow for the display name to be set in a 'Name' element. If this was set in the input BoM, its value is returned in this property. If the Name was not present in the input BoM, this property is omitted.

        Returns
        -------
        str
            The name of this GetImpactedSubstancesForPartsPart.
        """
        return self._name

    @name.setter
    def name(self, name: "str") -> None:
        """Sets the name of this GetImpactedSubstancesForPartsPart.
        Many elements in the input BoM schema allow for the display name to be set in a 'Name' element. If this was set in the input BoM, its value is returned in this property. If the Name was not present in the input BoM, this property is omitted.

        Parameters
        ----------
        name: str
            The name of this GetImpactedSubstancesForPartsPart.
        """
        self._name = name

    @property
    def reference_type(self) -> "str":
        """Gets the reference_type of this GetImpactedSubstancesForPartsPart.

        Returns
        -------
        str
            The reference_type of this GetImpactedSubstancesForPartsPart.
        """
        return self._reference_type

    @reference_type.setter
    def reference_type(self, reference_type: "str") -> None:
        """Sets the reference_type of this GetImpactedSubstancesForPartsPart.

        Parameters
        ----------
        reference_type: str
            The reference_type of this GetImpactedSubstancesForPartsPart.
        """
        self._reference_type = reference_type

    @property
    def reference_value(self) -> "str":
        """Gets the reference_value of this GetImpactedSubstancesForPartsPart.

        Returns
        -------
        str
            The reference_value of this GetImpactedSubstancesForPartsPart.
        """
        return self._reference_value

    @reference_value.setter
    def reference_value(self, reference_value: "str") -> None:
        """Sets the reference_value of this GetImpactedSubstancesForPartsPart.

        Parameters
        ----------
        reference_value: str
            The reference_value of this GetImpactedSubstancesForPartsPart.
        """
        self._reference_value = reference_value

    @property
    def id(self) -> "str":
        """Gets the id of this GetImpactedSubstancesForPartsPart.
        Many elements in the input BoM schema allow for an XML ID attribute (called 'id') to be set. If this was set in the input BoM, its value is returned in this property. If no value was set in the input BoM an arbitrary, a unique value will be assigned.

        Returns
        -------
        str
            The id of this GetImpactedSubstancesForPartsPart.
        """
        return self._id

    @id.setter
    def id(self, id: "str") -> None:
        """Sets the id of this GetImpactedSubstancesForPartsPart.
        Many elements in the input BoM schema allow for an XML ID attribute (called 'id') to be set. If this was set in the input BoM, its value is returned in this property. If no value was set in the input BoM an arbitrary, a unique value will be assigned.

        Parameters
        ----------
        id: str
            The id of this GetImpactedSubstancesForPartsPart.
        """
        self._id = id

    @classmethod
    def get_real_child_model(cls, data: ModelBase) -> str:
        """Raises a NotImplementedError for a type without a discriminator defined.

        Parameters
        ----------
        data: ModelBase
            Object representing a subclass of this class

        Raises
        ------
        NotImplementedError
            This class has no discriminator, and hence no subclasses
        """
        raise NotImplementedError()

    def __repr__(self) -> str:
        """For 'print' and 'pprint'"""
        return self.to_str()

    def __eq__(self, other: Any) -> bool:
        """Returns true if both objects are equal"""
        if not isinstance(other, GetImpactedSubstancesForPartsPart):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other: Any) -> bool:
        """Returns true if both objects are not equal"""
        return not self == other
