"""
    Granta.BomAnalyticsServices

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: V1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import re  # noqa: F401
from typing import TYPE_CHECKING, Any, Dict, List, Optional  # noqa: F401

from . import ModelBase


if TYPE_CHECKING:
    from . import *


class GetSustainabilityForBom2301Request(ModelBase):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes
    ----------
    swagger_types: Dict[str, str]
        The key is attribute name and the value is attribute type.
    attribute_map: Dict[str, str]
        The key is attribute name and the value is json key in definition.
    subtype_mapping: Dict[str, str]
        The key is the unmangled property name and the value is the corresponding type.
    discriminator: Optional[str]
        Name of the property used as discriminator for subtypes.
    """
    swagger_types = {
        "bom_xml2301": "str",
        "config": "CommonRequestConfig",
        "database_key": "str",
        "preferred_units": "CommonPreferredUnits",
    }

    attribute_map = {
        "bom_xml2301": "BomXml2301",
        "config": "Config",
        "database_key": "DatabaseKey",
        "preferred_units": "PreferredUnits",
    }

    subtype_mapping = {
        "PreferredUnits": "CommonPreferredUnits",
        "Config": "CommonRequestConfig",
    }

    discriminator = None

    def __init__(
        self,
        *,
        bom_xml2301: "Optional[str]" = None,
        config: "Optional[CommonRequestConfig]" = None,
        database_key: "Optional[str]" = None,
        preferred_units: "Optional[CommonPreferredUnits]" = None,
    ) -> None:
        """GetSustainabilityForBom2301Request - a model defined in Swagger

        Parameters
        ----------
            bom_xml2301: str, optional
            config: CommonRequestConfig, optional
            database_key: str, optional
            preferred_units: CommonPreferredUnits, optional
        """
        self._bom_xml2301 = None
        self._preferred_units = None
        self._database_key = None
        self._config = None

        if bom_xml2301 is not None:
            self.bom_xml2301 = bom_xml2301
        if preferred_units is not None:
            self.preferred_units = preferred_units
        if database_key is not None:
            self.database_key = database_key
        if config is not None:
            self.config = config

    @property
    def bom_xml2301(self) -> "str":
        """Gets the bom_xml2301 of this GetSustainabilityForBom2301Request.

        Returns
        -------
        str
            The bom_xml2301 of this GetSustainabilityForBom2301Request.
        """
        return self._bom_xml2301

    @bom_xml2301.setter
    def bom_xml2301(self, bom_xml2301: "str") -> None:
        """Sets the bom_xml2301 of this GetSustainabilityForBom2301Request.

        Parameters
        ----------
        bom_xml2301: str
            The bom_xml2301 of this GetSustainabilityForBom2301Request.
        """
        self._bom_xml2301 = bom_xml2301

    @property
    def preferred_units(self) -> "CommonPreferredUnits":
        """Gets the preferred_units of this GetSustainabilityForBom2301Request.

        Returns
        -------
        CommonPreferredUnits
            The preferred_units of this GetSustainabilityForBom2301Request.
        """
        return self._preferred_units

    @preferred_units.setter
    def preferred_units(self, preferred_units: "CommonPreferredUnits") -> None:
        """Sets the preferred_units of this GetSustainabilityForBom2301Request.

        Parameters
        ----------
        preferred_units: CommonPreferredUnits
            The preferred_units of this GetSustainabilityForBom2301Request.
        """
        self._preferred_units = preferred_units

    @property
    def database_key(self) -> "str":
        """Gets the database_key of this GetSustainabilityForBom2301Request.

        Returns
        -------
        str
            The database_key of this GetSustainabilityForBom2301Request.
        """
        return self._database_key

    @database_key.setter
    def database_key(self, database_key: "str") -> None:
        """Sets the database_key of this GetSustainabilityForBom2301Request.

        Parameters
        ----------
        database_key: str
            The database_key of this GetSustainabilityForBom2301Request.
        """
        self._database_key = database_key

    @property
    def config(self) -> "CommonRequestConfig":
        """Gets the config of this GetSustainabilityForBom2301Request.

        Returns
        -------
        CommonRequestConfig
            The config of this GetSustainabilityForBom2301Request.
        """
        return self._config

    @config.setter
    def config(self, config: "CommonRequestConfig") -> None:
        """Sets the config of this GetSustainabilityForBom2301Request.

        Parameters
        ----------
        config: CommonRequestConfig
            The config of this GetSustainabilityForBom2301Request.
        """
        self._config = config

    @classmethod
    def get_real_child_model(cls, data: ModelBase) -> str:
        """Raises a NotImplementedError for a type without a discriminator defined.

        Parameters
        ----------
        data: ModelBase
            Object representing a subclass of this class

        Raises
        ------
        NotImplementedError
            This class has no discriminator, and hence no subclasses
        """
        raise NotImplementedError()

    def __repr__(self) -> str:
        """For 'print' and 'pprint'"""
        return self.to_str()

    def __eq__(self, other: Any) -> bool:
        """Returns true if both objects are equal"""
        if not isinstance(other, GetSustainabilityForBom2301Request):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other: Any) -> bool:
        """Returns true if both objects are not equal"""
        return not self == other
