"""
    Granta.BomAnalyticsServices

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: V1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import re  # noqa: F401
from typing import TYPE_CHECKING, Any, Dict, List, Optional  # noqa: F401

from . import ModelBase


if TYPE_CHECKING:
    from . import *


class GetComplianceForBom1711Request(ModelBase):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes
    ----------
    swagger_types: Dict[str, str]
        The key is attribute name and the value is attribute type.
    attribute_map: Dict[str, str]
        The key is attribute name and the value is json key in definition.
    subtype_mapping: Dict[str, str]
        The key is the unmangled property name and the value is the corresponding type.
    discriminator: Optional[str]
        Name of the property used as discriminator for subtypes.
    """
    swagger_types = {
        "bom_xml1711": "str",
        "config": "CommonRequestConfig",
        "database_key": "str",
        "indicators": "list[CommonIndicatorDefinition]",
    }

    attribute_map = {
        "bom_xml1711": "BomXml1711",
        "config": "Config",
        "database_key": "DatabaseKey",
        "indicators": "Indicators",
    }

    subtype_mapping = {
        "Indicators": "CommonIndicatorDefinition",
        "Config": "CommonRequestConfig",
    }

    discriminator = None

    def __init__(
        self,
        *,
        bom_xml1711: "Optional[str]" = None,
        config: "Optional[CommonRequestConfig]" = None,
        database_key: "Optional[str]" = None,
        indicators: "Optional[List[CommonIndicatorDefinition]]" = None,
    ) -> None:
        """GetComplianceForBom1711Request - a model defined in Swagger

        Parameters
        ----------
            bom_xml1711: str, optional
            config: CommonRequestConfig, optional
            database_key: str, optional
            indicators: List[CommonIndicatorDefinition], optional
        """
        self._bom_xml1711 = None
        self._indicators = None
        self._database_key = None
        self._config = None

        if bom_xml1711 is not None:
            self.bom_xml1711 = bom_xml1711
        if indicators is not None:
            self.indicators = indicators
        if database_key is not None:
            self.database_key = database_key
        if config is not None:
            self.config = config

    @property
    def bom_xml1711(self) -> "str":
        """Gets the bom_xml1711 of this GetComplianceForBom1711Request.

        Returns
        -------
        str
            The bom_xml1711 of this GetComplianceForBom1711Request.
        """
        return self._bom_xml1711

    @bom_xml1711.setter
    def bom_xml1711(self, bom_xml1711: "str") -> None:
        """Sets the bom_xml1711 of this GetComplianceForBom1711Request.

        Parameters
        ----------
        bom_xml1711: str
            The bom_xml1711 of this GetComplianceForBom1711Request.
        """
        self._bom_xml1711 = bom_xml1711

    @property
    def indicators(self) -> "list[CommonIndicatorDefinition]":
        """Gets the indicators of this GetComplianceForBom1711Request.

        Returns
        -------
        list[CommonIndicatorDefinition]
            The indicators of this GetComplianceForBom1711Request.
        """
        return self._indicators

    @indicators.setter
    def indicators(self, indicators: "list[CommonIndicatorDefinition]") -> None:
        """Sets the indicators of this GetComplianceForBom1711Request.

        Parameters
        ----------
        indicators: list[CommonIndicatorDefinition]
            The indicators of this GetComplianceForBom1711Request.
        """
        self._indicators = indicators

    @property
    def database_key(self) -> "str":
        """Gets the database_key of this GetComplianceForBom1711Request.

        Returns
        -------
        str
            The database_key of this GetComplianceForBom1711Request.
        """
        return self._database_key

    @database_key.setter
    def database_key(self, database_key: "str") -> None:
        """Sets the database_key of this GetComplianceForBom1711Request.

        Parameters
        ----------
        database_key: str
            The database_key of this GetComplianceForBom1711Request.
        """
        self._database_key = database_key

    @property
    def config(self) -> "CommonRequestConfig":
        """Gets the config of this GetComplianceForBom1711Request.

        Returns
        -------
        CommonRequestConfig
            The config of this GetComplianceForBom1711Request.
        """
        return self._config

    @config.setter
    def config(self, config: "CommonRequestConfig") -> None:
        """Sets the config of this GetComplianceForBom1711Request.

        Parameters
        ----------
        config: CommonRequestConfig
            The config of this GetComplianceForBom1711Request.
        """
        self._config = config

    @classmethod
    def get_real_child_model(cls, data: ModelBase) -> str:
        """Raises a NotImplementedError for a type without a discriminator defined.

        Parameters
        ----------
        data: ModelBase
            Object representing a subclass of this class

        Raises
        ------
        NotImplementedError
            This class has no discriminator, and hence no subclasses
        """
        raise NotImplementedError()

    def __repr__(self) -> str:
        """For 'print' and 'pprint'"""
        return self.to_str()

    def __eq__(self, other: Any) -> bool:
        """Returns true if both objects are equal"""
        if not isinstance(other, GetComplianceForBom1711Request):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other: Any) -> bool:
        """Returns true if both objects are not equal"""
        return not self == other
