# coding: utf-8

"""
    Granta.BomAnalyticsServices

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: V1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pytest  # noqa: F401
from ansys.grantami.bomanalytics_openapi.models import (
    GetComplianceForBom1711Response,
)  # noqa: E501
from .mocked_tests import generate_model


def test_GetComplianceForBom1711Response():
    """Test GetComplianceForBom1711Response"""

    model = generate_model(GetComplianceForBom1711Response)
    assert model
