# coding: utf-8

"""
    Granta.BomAnalyticsServices

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: V1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pytest  # noqa: F401
from ansys.grantami.bomanalytics_openapi.models import (
    GetSustainabilityForBom2301Response,
)  # noqa: E501
from .mocked_tests import generate_model


def test_GetSustainabilityForBom2301Response():
    """Test GetSustainabilityForBom2301Response"""

    model = generate_model(GetSustainabilityForBom2301Response)
    assert model
