# coding: utf-8

"""
    Granta.BomAnalyticsServices

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: V1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pytest
import ansys.openapi.common as auth
import GrantaBomSvcs.models as models

@pytest.fixture(scope="session")
def api_client():
    api_client = auth.ApiClientFactory("http://localhost/mi_servicelayer").with_autologon().build()
    api_client.setup_client(models)
    return api_client
