# coding: utf-8

"""
    Granta.BomAnalyticsServices

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: V1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pytest  # noqa: F401
from GrantaBomSvcs.models import GrantaBomAnalyticsServicesInterfaceGetComplianceForBom1711Response  # noqa: E501
from .common import generate_model



def test_GrantaBomAnalyticsServicesInterfaceGetComplianceForBom1711Response():
    """Test GrantaBomAnalyticsServicesInterfaceGetComplianceForBom1711Response"""

    model = generate_model(GrantaBomAnalyticsServicesInterfaceGetComplianceForBom1711Response)
    assert model

