name: Build and Test Client Library
on:
  push:
    tags:
      - "*"
    paths:
      - "ansys-grantami-bomanalytics-openapi"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install build requirements
        run: pip install build wheel

      - name: Create local deps folder
        run: |
          cd ansys-grantami-bomanalytics-openapi
          mkdir -p deps

      - name: Copy client common wheel
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{secrets.CLIENT_COMMON_REPO_TOKEN}}
          workflow: ci_cd.yml
          workflow_conclusion: success
          name: ansys-grantami-common-wheel
          path: ansys-grantami-bomanalytics-openapi/deps
          repo: pyansys/openapi-common
          check_artifacts: false
          search_artifacts: false

      - name: Create wheel
        working-directory: ansys-grantami-bomanalytics-openapi
        run: python -m build

      - name: Validate wheel
        if: ${{ false }}
        working-directory: ansys-grantami-bomanalytics-openapi
        run: |
          pip install twine
          twine check dist/*

      - name: Upload wheel artifact
        uses: actions/upload-artifact@v2
        with:
          name: ansys-grantami-bomanalytics-openapi-wheel
          path: ansys-grantami-bomanalytics-openapi/dist/
          retention-days: 7

  test:
    name: Unit test on supported platforms
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.6', '3.7', '3.8', '3.9', '3.10' ]
    steps:
      - uses: actions/checkout@v1

      - name: Install kerberos headers
        run: sudo apt install libkrb5-dev

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Create local deps folder
        run: |
          cd ansys-grantami-bomanalytics-openapi
          mkdir -p deps

      - name: Copy client common wheel
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{secrets.CLIENT_COMMON_REPO_TOKEN}}
          workflow: ci_cd.yml
          workflow_conclusion: success
          name: ansys-grantami-common-wheel
          path: ansys-grantami-bomanalytics-openapi/deps
          repo: pyansys/openapi-common
          check_artifacts: false
          search_artifacts: false

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox tox-gh-actions

      - name: Test with tox
        working-directory: ansys-grantami-bomanalytics-openapi
        run: |
          tox
