name: Generate Library and Create PR

# run only on main branch.  This avoids duplicated actions on PRs
on:
  push:
    tags:
    - "*"
    branches:
    - main
    paths:
    - 'yaml/*.yaml'
    - 'pom.xml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven
      
    - name: Build client library
      run: mvn -Dbuild-id=${{ github.run_id }} -s .m2/settings.xml compile
      env:
        SERVER_USERNAME: ${{ secrets.REPO_USER }}
        SERVER_PASSWORD: ${{ secrets.REPO_TOKEN }}
        
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        commit-message: Update client library
        committer: GitHub <noreply@github.com>
        author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
        signoff: false
        branch: client-library-build
        delete-branch: true
        title: 'Update client library'
        body: |
          Update library with new YAML interface definition
        labels: |
          automated
        team-reviewers: |
          Maintainers
