name: GitHub CI

# run only on main branch.  This avoids duplicated actions on PRs
on:
  push:
    tags:
    - "*"
    branches:
    - main
    paths:
    - 'yaml/*.yaml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven
      
    - name: Deploy package to github packages
      run: mvn compile
      env:
        SERVER_USERNAME: ${{ secrets.REPO_USER }}
        SERVER_PASSWORD: ${{ secrets.REPO_TOKEN }}